export const ErrorCode = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMIT_ERROR: "RATE_LIMIT_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_USER_NOT_VERIFIED: "AUTH_USER_NOT_VERIFIED",
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
